version: '3.8'

services:
  note:
    build: ./note
    container_name: note-container
    ports:
      - "8082:8082"
    networks:
      - my-network
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_DATABASE: NoteDB
      SPRING_DATA_MONGODB_PORT: 27017
    volumes:
      - note-data:/data/db

  patient-service:
    build: ./patient
    ports:
      - "8081:8081"
    networks:
      - my-network
    depends_on:
      - mysqldb
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/medilabo"
      - "SPRING_DATASOURCE_USERNAME=root"
      - "SPRING_DATASOURCE_PASSWORD=password"
    volumes:
      - patient-data:/var/lib/mysql
#    restart: on-failure

  report-risk:
    build: ./report-risk
    container_name: report-risk-container
    ports:
      - "8084:8084"
    networks:
      - my-network

  gateway:
    build: ./gateway
    container_name: gateway-container
    ports:
      - "8080:8080"
    networks:
      - my-network

  front:
    build: ./front
    container_name: front-container
    ports:
      - "8090:8090"
    networks:
      - my-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - my-network
    volumes:
      - mongo-data:/data/db

  mysqldb:
    image: mysql:8.0.32
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=medilabo
#      - MYSQL_USER=
#      - MYSQL_PASSWORD=
    ports:
      - "3307:3306"
    networks:
      - my-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  my-network:

volumes:
  mongo-data:
  mysql-data:
  note-data:
  patient-data:


#local
#services:
#  front:
#    build: ./front
#    ports:
#      - "8090:8090"
#
#  gateway:
#    build: ./gateway
#    ports:
#      - "8080:8080"
#
#  patient:
#    build: ./patient
#    ports:
#      - "8081:8081"
#
#  note:
#    build: ./note
#    ports:
#      - "8082:8082"
#
#  report-risk:
#    build: ./report-risk
#    ports:
#      - "8084:8084"
#  mongodb:
#    image: mongo
#    container_name: mongodb
#    ports:
#      - "27017:27017"

#version: '3'
#
#services:
#  front:
#    build: ./front
#    ports:
#      - "8090:8090"
#    networks:
#      - my-network
#
#  gateway:
#    build: ./gateway
#    ports:
#      - "8080:8080"
#    networks:
#      - my-network
#    depends_on:
#      - patient
#      - note
#
#  patient:
#    build: ./patient
#    ports:
#      - "8081:8081"
#    networks:
#      - my-network
#    depends_on:
#      - mysql
#
#  note:
#    build: ./note
#    ports:
#      - "8082:8082"
#    networks:
#      - my-network
#
#  report-risk:
#    build: ./report-risk
#    ports:
#      - "8084:8084"
#    networks:
#      - my-network
#
#  mysql:
#    image: mysql:latest
#    container_name: mysql
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: medilabo
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#    networks:
#      - my-network
#
#networks:
#  my-network:
#    driver: bridge
