server:
  port: 8080


spring:
  cloud:
    gateway:
      routes:
        - id: patient
          uri: http://localhost:8081
          predicates:
            - Path=/patient/**
        - id: note
          uri: http://localhost:8082
          predicates:
            - Path=/note/**
        - id: diagnostic
          uri: http://localhost:8084
          predicates:
            - Path=/diagnostic/**
#eureka:
#  instance:
#    hostname: localhost

